version: '3.8'

services:
  expo:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
      - '19000:19000' 
      - '19001:19001' 
      - '19002:19002' 
    volumes:
      - ./client:/app 
      - /app/node_modules
    stdin_open: true
    tty: true
    environment:
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
    command: npx expo start
